### ISSUE TITLE
question

### ISSUE THREAD

**Issue by JiaRuibo** [abustaoglu/ImageBinarization-FuzzyPixelRepresentation#1]
histogram_h can not run in matlab2020

**Comment by abustaoglu** [comment]
I have uploaded histogram_h.m file. Can you try to run this repo again and tell me if it's work?

**Comment by JiaRuibo** [comment]
yes，It's running successfully，I used imhist instead of histogram_h.



At 2021-12-17 04:53:55, "Ahmet Burak" ***@***.***> wrote:

I have uploaded histogram_h.m file. Can you try to run this repo again and tell me if it's work working?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
